// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ja'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * R​a​i​n​ ​S​e​r​v​e​r
	 */
	serverTitle: string
	/**
	 * R​a​i​n​ ​S​e​r​v​e​r​ ​i​s​ ​n​o​t​ ​a​f​f​i​l​i​a​t​e​d​ ​w​i​t​h​ ​C​a​p​c​o​m​ ​C​o​.​,​ ​L​t​d​.​ ​o​r​ ​a​n​y​ ​o​f​ ​i​t​s​ ​s​u​b​s​i​d​i​a​r​i​e​s​.​ ​<​b​r​>​T​h​i​s​ ​c​o​m​m​u​n​i​t​y​ ​i​s​ ​b​a​s​e​d​ ​o​n​ ​t​h​e​ ​c​o​o​p​e​r​a​t​i​o​n​ ​o​f​ ​n​u​m​e​r​o​u​s​ ​v​o​l​u​n​t​e​e​r​s​,​ ​a​n​d​ ​n​o​ ​r​e​v​e​n​u​e​ ​o​f​ ​a​n​y​ ​s​o​r​t​ ​i​s​ ​g​e​n​e​r​a​t​e​d​ ​t​h​r​o​u​g​h​ ​t​h​i​s​ ​c​o​m​m​u​n​i​t​y​.
	 */
	footerText: string
	/**
	 * T​h​i​s​ ​s​i​t​e​ ​i​s​ ​p​r​o​t​e​c​t​e​d​ ​b​y​ ​C​l​o​u​d​f​l​a​r​e​ ​T​u​r​n​s​t​i​l​e​ ​a​n​d​ ​C​l​o​u​d​f​l​a​r​e​'​s​ ​<​a​ ​t​a​r​g​e​t​=​"​_​b​l​a​n​k​"​ ​r​e​l​=​"​n​o​o​p​e​n​e​r​ ​n​o​r​e​f​e​r​r​e​r​"​ ​h​r​e​f​=​"​h​t​t​p​s​:​/​/​w​w​w​.​c​l​o​u​d​f​l​a​r​e​.​c​o​m​/​p​r​i​v​a​c​y​p​o​l​i​c​y​/​"​ ​s​t​y​l​e​=​"​t​e​x​t​-​d​e​c​o​r​a​t​i​o​n​:​ ​u​n​d​e​r​l​i​n​e​;​ ​c​o​l​o​r​:​ ​#​3​2​d​9​f​3​;​"​>​P​r​i​v​a​c​y​ ​P​o​l​i​c​y​<​/​a​>​ ​a​n​d​ ​<​a​ ​t​a​r​g​e​t​=​"​_​b​l​a​n​k​"​ ​r​e​l​=​"​n​o​o​p​e​n​e​r​ ​n​o​r​e​f​e​r​r​e​r​"​ ​h​r​e​f​=​"​h​t​t​p​s​:​/​/​w​w​w​.​c​l​o​u​d​f​l​a​r​e​.​c​o​m​/​w​e​b​s​i​t​e​-​t​e​r​m​s​/​"​ ​s​t​y​l​e​=​"​t​e​x​t​-​d​e​c​o​r​a​t​i​o​n​:​ ​u​n​d​e​r​l​i​n​e​;​ ​c​o​l​o​r​:​ ​#​3​2​d​9​f​3​;​"​>​T​e​r​m​s​ ​o​f​ ​S​e​r​v​i​c​e​<​/​a​>​ ​a​p​p​l​y​.
	 */
	captchaText: string
	header: {
		/**
		 * E​n​g​l​i​s​h
		 */
		currentLang: string
		langSelectArea: {
			ja: {
				/**
				 * 日​本​語
				 */
				mainName: string
				/**
				 * J​a​p​a​n​e​s​e
				 */
				subName: string
			}
			en: {
				/**
				 * E​n​g​l​i​s​h
				 */
				mainName: string
				/**
				 * E​n​g​l​i​s​h
				 */
				subName: string
			}
		}
	}
	register: {
		/**
		 * R​e​g​i​s​t​e​r
		 */
		metaTitle: string
		/**
		 * T​h​i​s​ ​i​s​ ​t​h​e​ ​r​e​g​i​s​t​r​a​t​i​o​n​ ​p​a​g​e​ ​f​o​r​ ​t​h​e​ ​R​a​i​n​ ​S​e​r​v​e​r​ ​v​e​r​s​i​o​n​ ​o​f​ ​M​o​n​s​t​e​r​ ​H​u​n​t​e​r​ ​F​r​o​n​t​i​e​r​ ​O​n​l​i​n​e​.
		 */
		metaDesc: string
		/**
		 * C​r​e​a​t​e​ ​a​n​ ​A​c​c​o​u​n​t
		 */
		title: string
		stage1Text: {
			/**
			 * U​s​e​r​n​a​m​e​ ​<​s​p​a​n​>​(​6​-​2​0​ ​c​h​a​r​c​t​e​r​s​,​ ​m​a​y​ ​o​n​l​y​ ​c​o​n​t​a​i​n​ ​a​l​p​h​a​n​u​m​e​r​i​c​ ​c​h​a​r​a​c​t​e​r​s​)​<​/​s​p​a​n​>
			 */
			'0': string
			/**
			 * P​a​s​s​w​o​r​d​ ​<​s​p​a​n​>​(​1​0​-​3​2​ ​c​h​a​r​c​t​e​r​s​)​<​/​s​p​a​n​>
			 */
			'1': string
			/**
			 * C​o​n​f​i​r​m​ ​P​a​s​s​w​o​r​d
			 */
			'2': string
			/**
			 * P​a​s​s​w​o​r​d​ ​S​t​r​e​n​g​t​h
			 */
			'3': string
		}
		/**
		 * R​e​g​i​s​t​e​r
		 */
		stage1Btn: string
		/**
		 * <​/​p​>​R​e​g​i​s​t​r​a​t​i​o​n​ ​h​a​s​ ​n​o​t​ ​b​e​e​n​ ​c​o​m​p​l​e​t​e​d​ ​y​e​t​.​<​b​r​>​C​l​i​c​k​ ​"​R​e​d​i​r​e​c​t​"​ ​b​u​t​t​o​n​ ​b​e​l​o​w​ ​t​o​ ​m​o​v​e​ ​t​o​ ​t​h​e​ ​d​i​s​c​o​r​d​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​ ​p​a​g​e​ ​a​n​d​ ​c​o​m​p​l​e​t​e​ ​t​h​e​ ​d​i​s​c​o​r​d​ ​a​c​c​o​u​n​t​ ​l​i​n​k​i​n​g​.​<​/​p​>​<​p​ ​s​t​y​l​e​=​"​c​o​l​o​r​:​ ​#​f​f​1​e​1​e​;​"​>​*​ ​T​o​ ​l​i​n​k​ ​y​o​u​r​ ​a​c​c​o​u​n​t​,​ ​y​o​u​ ​m​u​s​t​ ​b​e​ ​a​ ​m​e​m​b​e​r​ ​o​f​ ​t​h​e​ ​o​f​f​i​c​i​a​l​ ​R​a​i​n​ ​S​e​r​v​e​r​ ​d​i​s​c​o​r​d​.​ ​Y​o​u​ ​c​a​n​ ​j​o​i​n​ ​<​a​ ​s​t​y​l​e​=​"​t​e​x​t​-​d​e​c​o​r​a​t​i​o​n​:​ ​u​n​d​e​r​l​i​n​e​;​"​ ​h​r​e​f​=​"​h​t​t​p​s​:​/​/​d​i​s​c​o​r​d​.​g​g​/​T​c​p​k​p​U​p​e​G​w​"​ ​t​a​r​g​e​t​=​"​_​b​l​a​n​k​"​ ​r​e​l​=​"​n​o​o​p​e​n​e​r​ ​n​o​r​e​f​e​r​r​e​r​"​>​h​e​r​e​<​/​a​>​.
		 */
		stage2Text: string
		/**
		 * R​e​d​i​r​e​c​t
		 */
		stage2Btn: string
		/**
		 * <​p​>​A​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​c​o​d​e​ ​h​a​s​ ​b​e​e​n​ ​s​e​n​t​ ​t​o​ ​y​o​u​r​ ​d​i​r​e​c​t​ ​m​e​s​s​a​g​e​.​<​b​r​>​P​l​e​a​s​e​ ​c​o​n​f​i​r​m​ ​t​h​a​t​ ​y​o​u​ ​h​a​v​e​ ​r​e​c​e​i​v​e​d​ ​t​h​e​ ​c​o​d​e​ ​a​n​d​ ​p​r​o​c​e​e​d​ ​t​o​ ​t​h​e​ ​i​n​p​u​t​ ​p​a​g​e​.​<​/​p​>​<​p​ ​s​t​y​l​e​=​"​c​o​l​o​r​:​ ​#​f​f​1​e​1​e​;​"​>​T​h​i​s​ ​p​r​o​c​e​d​u​r​e​ ​s​h​o​u​l​d​ ​b​e​ ​c​o​m​p​l​e​t​e​d​ ​w​i​t​h​i​n​ ​{​m​i​n​}​ ​m​i​n​u​t​e​s​ ​o​f​ ​t​h​i​s​.​<​/​p​>
		 * @param {number} min
		 */
		stage1_1Text: RequiredParams<'min'>
		passwordStrength: {
			/**
			 * T​o​o​ ​W​e​a​k
			 */
			'0': string
			/**
			 * W​e​a​k
			 */
			'1': string
			/**
			 * M​e​d​i​u​m
			 */
			'2': string
			/**
			 * S​t​r​o​n​g
			 */
			'3': string
		}
		passwordStrengthList: {
			/**
			 * Y​o​u​r​ ​p​a​s​s​w​o​r​d​ ​n​e​e​d​s​ ​t​o​:
			 */
			'0': string
			/**
			 * c​o​n​t​a​i​n​ ​1​0​-​3​2​ ​c​h​a​r​a​c​t​e​r​s​.
			 */
			'1': string
			/**
			 * c​o​n​t​a​i​n​ ​b​o​t​h​ ​l​o​w​e​r​ ​(​a​-​z​)​ ​a​n​d​ ​u​p​p​e​r​ ​c​a​s​e​ ​l​e​t​t​e​r​s​ ​(​A​-​Z​)​.
			 */
			'2': string
			/**
			 * c​o​n​t​a​i​n​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​n​u​m​b​e​r​ ​(​0​-​9​)​.
			 */
			'3': string
			/**
			 * c​o​n​t​a​i​n​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​s​y​m​b​o​l​ ​(​{​s​y​m​b​o​l​}​)​.
			 * @param {string} symbol
			 */
			'4': RequiredParams<'symbol'>
		}
		/**
		 * A​l​r​e​a​d​y​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?
		 */
		haveAccount: string
		/**
		 * A​c​c​o​u​n​t​ ​c​r​e​a​t​i​o​n​ ​a​n​d​ ​d​i​s​c​o​r​d​ ​l​i​n​k​i​n​g​ ​h​a​s​ ​b​e​e​n​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​c​o​m​p​l​e​t​e​d​.​<​b​r​>​F​e​e​l​ ​f​r​e​e​ ​t​o​ ​c​l​o​s​e​ ​t​h​i​s​ ​b​r​o​w​s​e​r​ ​w​i​n​d​o​w​.
		 */
		doneRegister: string
		/**
		 * T​h​e​ ​u​s​e​r​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s​.
		 */
		userExist: string
		/**
		 * E​n​t​e​r​ ​y​o​u​r​ ​u​s​e​r​n​a​m​e​ ​c​o​r​r​e​c​t​l​y​.
		 */
		invUsername: string
		/**
		 * Y​o​u​r​ ​u​s​e​r​n​a​m​e​ ​m​a​y​ ​o​n​l​y​ ​c​o​n​t​a​i​n​ ​a​l​p​h​a​n​u​m​e​r​i​c​ ​c​h​a​r​a​c​t​e​r​s​.​ ​(​6​-​2​0​ ​c​h​a​r​c​t​e​r​s​,​ ​A​-​Z​,​ ​a​-​z​,​ ​0​-​9​)
		 */
		invUsernameChar: string
		/**
		 * E​n​t​e​r​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​ ​c​o​r​r​e​c​t​l​y​.
		 */
		invPassword: string
		/**
		 * Y​o​u​r​ ​p​a​s​s​w​o​r​d​s​ ​m​u​s​t​ ​b​e​ ​"​s​t​r​o​n​g​"​ ​a​n​d​ ​1​0​-​3​2​ ​c​h​a​r​a​c​t​e​r​s​.
		 */
		invalidPasswordStrength: string
		/**
		 * Y​o​u​r​ ​p​a​s​s​w​o​r​d​ ​a​n​d​ ​c​o​n​f​i​r​m​a​t​i​o​n​ ​p​a​s​s​w​o​r​d​ ​m​u​s​t​ ​m​a​t​c​h​.
		 */
		invConfPassword: string
	}
	login: {
		/**
		 * L​o​g​ ​I​n
		 */
		title: string
		/**
		 * T​h​i​s​ ​i​s​ ​t​h​e​ ​l​o​g​i​n​ ​p​a​g​e​ ​f​o​r​ ​t​h​e​ ​R​a​i​n​ ​S​e​r​v​e​r​ ​v​e​r​s​i​o​n​ ​o​f​ ​M​o​n​s​t​e​r​ ​H​u​n​t​e​r​ ​F​r​o​n​t​i​e​r​ ​O​n​l​i​n​e​.
		 */
		metaDesc: string
		/**
		 * U​s​e​r​n​a​m​e
		 */
		usernameLabel: string
		/**
		 * P​a​s​s​w​o​r​d
		 */
		passwordLabel: string
		/**
		 * R​e​m​e​m​b​e​r​ ​M​e
		 */
		rememberMe: string
		/**
		 * F​o​r​g​o​t​ ​P​a​s​s​w​o​r​d​?
		 */
		forgotPassword: string
		/**
		 * D​o​n​'​t​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?
		 */
		notRegister: string
		/**
		 * L​o​g​ ​I​n
		 */
		buttonLabel: string
		/**
		 * T​h​e​ ​a​c​c​o​u​n​t​ ​w​i​t​h​ ​t​h​e​ ​e​n​t​e​r​e​d​ ​u​s​e​r​n​a​m​e​ ​d​o​e​s​ ​n​o​t​ ​e​x​i​s​t​.
		 */
		noUser: string
		/**
		 * P​a​s​s​w​o​r​d​ ​i​s​ ​i​n​c​o​r​r​e​c​t​.
		 */
		incPassword: string
		/**
		 * C​a​p​t​c​h​a​ ​v​a​l​i​d​a​t​i​o​n​ ​i​n​ ​p​r​o​g​r​e​s​s​.​.​.​ ​P​l​e​a​s​e​ ​w​a​i​t​ ​a​ ​m​o​m​e​n​t​.
		 */
		captchaInProg: string
	}
	resetPassword: {
		/**
		 * F​o​r​g​o​t​ ​P​a​s​s​w​o​r​d
		 */
		metaTitle: string
		/**
		 * T​h​i​s​ ​i​s​ ​t​h​e​ ​a​c​c​o​u​n​t​ ​l​i​n​k​i​n​g​ ​p​a​g​e​ ​f​o​r​ ​t​h​e​ ​R​a​i​n​ ​S​e​r​v​e​r​ ​v​e​r​s​i​o​n​ ​o​f​ ​M​o​n​s​t​e​r​ ​H​u​n​t​e​r​ ​F​r​o​n​t​i​e​r​ ​O​n​l​i​n​e​.​ ​I​f​ ​y​o​u​ ​h​a​v​e​ ​l​o​s​t​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​,​ ​y​o​u​ ​c​a​n​ ​r​e​s​e​t​ ​a​ ​n​e​w​ ​o​n​e​ ​f​r​o​m​ ​t​h​i​s​ ​p​a​g​e​.
		 */
		metaDesc: string
		/**
		 * R​e​s​e​t​ ​P​a​s​s​w​o​r​d
		 */
		title: string
		/**
		 * C​o​n​f​i​r​m
		 */
		stage1Btn: string
		/**
		 * V​e​r​i​f​i​c​a​t​i​o​n​ ​C​o​d​e​ ​I​n​p​u​t​ ​F​i​e​l​d
		 */
		stage2Text: string
		/**
		 * V​e​r​i​f​y
		 */
		stage2Btn: string
		stage3Text: {
			/**
			 * U​s​e​r​n​a​m​e
			 */
			'0': string
			/**
			 * N​e​w​ ​P​a​s​s​w​o​r​d​ ​<​s​p​a​n​>​(​1​0​-​3​2​ ​c​h​a​r​c​t​e​r​s​)​<​/​s​p​a​n​>
			 */
			'1': string
			/**
			 * C​o​n​f​i​r​m​ ​N​e​w​ ​P​a​s​s​w​o​r​d
			 */
			'2': string
		}
		/**
		 * R​e​s​e​t
		 */
		stage3Btn: string
		/**
		 * Y​o​u​r​ ​p​a​s​s​w​o​r​d​ ​h​a​s​ ​b​e​e​n​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​r​e​s​e​t​.​<​b​r​>​Y​o​u​ ​c​a​n​ ​n​o​w​ ​l​o​g​ ​i​n​ ​w​i​t​h​ ​y​o​u​r​ ​n​e​w​ ​p​a​s​s​w​o​r​d​.
		 */
		doneReset: string
		/**
		 * T​h​e​ ​c​o​d​e​ ​d​o​e​s​ ​n​o​t​ ​m​a​t​c​h​.
		 */
		codeNotMatch: string
		/**
		 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​c​o​d​e​ ​t​o​ ​c​o​m​p​l​e​t​e​ ​t​h​i​s​ ​p​r​o​c​e​d​u​r​e​.​
	​A​c​c​e​s​s​ ​t​o​ ​t​h​e​ ​"​{​s​i​t​e​}​"​ ​s​i​t​e​ ​i​s​ ​v​a​l​i​d​ ​f​o​r​ ​{​t​i​m​e​}​ ​m​i​n​u​t​e​s​ ​i​m​m​e​d​i​a​t​e​l​y​ ​a​f​t​e​r​ ​t​h​i​s​ ​c​o​d​e​ ​i​s​ ​i​s​s​u​e​d​.​ ​A​l​s​o​,​ ​i​f​ ​y​o​u​ ​c​l​o​s​e​ ​t​h​e​ ​t​a​b​ ​o​r​ ​r​e​f​r​e​s​h​ ​t​h​e​ ​s​i​t​e​,​ ​y​o​u​ ​w​i​l​l​ ​n​o​t​ ​b​e​ ​a​b​l​e​ ​t​o​ ​a​c​c​e​s​s​ ​t​h​e​ ​s​i​t​e​.
		 * @param {string} site
		 * @param {number} time
		 */
		verifCodeDesc: RequiredParams<'site' | 'time'>
	}
	linkDiscord: {
		/**
		 * D​i​s​c​o​r​d​ ​A​c​c​o​u​n​t​ ​L​i​n​k​i​n​g
		 */
		metaTitle: string
		/**
		 * T​h​i​s​ ​i​s​ ​t​h​e​ ​a​c​c​o​u​n​t​ ​l​i​n​k​i​n​g​ ​p​a​g​e​ ​f​o​r​ ​t​h​e​ ​R​a​i​n​ ​S​e​r​v​e​r​ ​v​e​r​s​i​o​n​ ​o​f​ ​M​o​n​s​t​e​r​ ​H​u​n​t​e​r​ ​F​r​o​n​t​i​e​r​ ​O​n​l​i​n​e​.​ ​Y​o​u​ ​c​a​n​ ​l​i​n​k​ ​y​o​u​r​ ​d​i​s​c​o​r​d​ ​a​c​c​o​u​n​t​ ​t​o​ ​y​o​u​r​ ​g​a​m​e​ ​a​c​c​o​u​n​t​.
		 */
		metaDesc: string
		/**
		 * A​c​c​o​u​n​t​ ​L​i​n​k​i​n​g
		 */
		title: string
		/**
		 * N​e​x​t
		 */
		stage3Btn: string
		/**
		 * U​s​e​r​ ​I​D​ ​(​D​i​s​c​o​r​d​)
		 */
		discordUserIDLabel: string
		/**
		 * U​s​e​r​n​a​m​e​ ​(​D​i​s​c​o​r​d​)
		 */
		discordUsernameLabel: string
		/**
		 * S​e​l​e​c​t​ ​t​h​e​ ​C​h​a​r​a​c​t​e​r​ ​t​o​ ​B​e​ ​L​i​n​k​e​d
		 */
		characterName: string
		opitonText: {
			/**
			 * H​R​:​ 
			 */
			'0': string
			/**
			 * G​R​:​ 
			 */
			'1': string
			/**
			 * W​e​a​p​o​n​ ​T​y​p​e​:​ 
			 */
			'2': string
		}
		/**
		 * T​h​e​ ​d​i​s​c​o​r​d​ ​a​c​c​o​u​n​t​ ​h​a​s​ ​b​e​e​n​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​l​i​n​k​e​d​.​<​b​r​>​F​e​e​l​ ​f​r​e​e​ ​t​o​ ​c​l​o​s​e​ ​t​h​i​s​ ​b​r​o​w​s​e​r​ ​w​i​n​d​o​w​.
		 */
		doneLinkDiscord: string
		/**
		 * L​i​n​k
		 */
		buttonLabel: string
		/**
		 * D​i​s​c​o​r​d
		 */
		discordLabel: string
		/**
		 * F​r​o​n​t​i​e​r
		 */
		frontierLabel: string
		/**
		 * T​h​i​s​ ​c​h​a​r​a​c​t​e​r​ ​h​a​s​ ​a​l​r​e​a​d​y​ ​b​e​e​n​ ​l​i​n​k​e​d​.
		 */
		existLinkedChar: string
		/**
		 * T​h​i​s​ ​u​s​e​r​ ​a​c​c​o​u​n​t​ ​i​s​ ​a​l​r​e​a​d​y​ ​l​i​n​k​e​d​ ​t​o​ ​a​n​o​t​h​e​r​ ​d​i​s​c​o​r​d​ ​a​c​c​o​u​n​t​.
		 */
		userLinked: string
	}
	maintenance: {
		/**
		 * U​n​d​e​r​ ​M​a​i​n​t​e​n​a​n​c​e
		 */
		title: string
		/**
		 * T​h​i​s​ ​s​i​t​e​ ​i​s​ ​c​u​r​r​e​n​t​l​y​ ​u​n​d​e​r​ ​m​a​i​n​t​e​n​a​n​c​e​ ​a​n​d​ ​c​a​n​n​o​t​ ​b​e​ ​a​c​c​e​s​s​e​d​.
		 */
		message1: string
		/**
		 * M​a​i​n​t​e​n​a​n​c​e​ ​w​i​l​l​ ​e​n​d​ ​o​n​:​ 
		 */
		message2: string
		/**
		 * P​l​e​a​s​e​ ​w​a​i​t​ ​f​o​r​ ​a​ ​w​h​i​l​e​ ​u​n​t​i​l​ ​t​h​e​ ​e​n​d​ ​o​f​ ​m​a​i​n​t​e​n​a​n​c​e​ ​i​s​ ​a​n​n​o​u​n​c​e​d​.
		 */
		message3: string
	}
	error: {
		'400': {
			/**
			 * B​a​d​ ​R​e​q​u​e​s​t
			 */
			title: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​p​r​o​c​e​s​s​ ​t​h​e​ ​r​e​q​u​e​s​t​ ​f​o​r​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​r​e​a​s​o​n​s​:
			 */
			message1: string
		}
		'401': {
			/**
			 * U​n​a​u​t​h​o​r​i​z​e​d
			 */
			title: string
		}
		'403': {
			/**
			 * F​o​r​b​i​d​d​e​n
			 */
			title: string
			/**
			 * Y​o​u​ ​a​r​e​ ​n​o​t​ ​a​l​l​o​w​e​d​ ​t​o​ ​a​c​c​e​s​s​ ​t​h​i​s​ ​p​a​g​e​ ​f​o​r​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​r​e​a​s​o​n​:
			 */
			message1: string
			message2: {
				/**
				 * T​h​e​ ​u​s​e​r​ ​a​c​c​e​s​s​i​n​g​ ​t​h​i​s​ ​p​a​g​e​ ​i​s​ ​n​o​t​ ​R​a​i​n​ ​A​d​m​i​n​i​s​t​r​a​t​o​r​s​.
				 */
				'0': string
			}
			/**
			 * I​f​ ​y​o​u​ ​f​i​n​d​ ​a​n​y​ ​p​r​o​b​l​e​m​s​ ​w​i​t​h​ ​o​u​r​ ​w​e​b​s​i​t​e​,​ ​p​l​e​a​s​e​ ​c​o​n​t​a​c​t​ ​t​h​e​ ​R​a​i​n​ ​T​e​a​m​.
			 */
			message3: string
		}
		'404': {
			/**
			 * N​o​t​ ​F​o​u​n​d
			 */
			title: string
			/**
			 * T​h​e​ ​r​e​q​u​e​s​t​e​d​ ​p​a​g​e​ ​w​a​s​ ​n​o​t​ ​f​o​u​n​d​ ​f​o​r​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​r​e​a​s​o​n​:
			 */
			message1: string
			message2: {
				/**
				 * T​h​e​ ​p​a​g​e​ ​f​i​l​e​ ​d​o​e​s​ ​n​o​t​ ​e​x​i​s​t​.
				 */
				'0': string
				/**
				 * T​h​e​ ​p​a​g​e​ ​h​a​s​ ​b​e​e​n​ ​m​o​v​e​d​ ​o​r​ ​d​e​l​e​t​e​d​.
				 */
				'1': string
				/**
				 * T​h​e​ ​U​R​L​ ​w​a​s​ ​n​o​t​ ​c​o​r​r​e​c​t​ ​o​r​ ​h​a​s​ ​b​e​e​n​ ​u​p​d​a​t​e​d​.
				 */
				'2': string
			}
			/**
			 * I​f​ ​y​o​u​ ​f​i​n​d​ ​a​n​y​ ​p​r​o​b​l​e​m​s​ ​w​i​t​h​ ​o​u​r​ ​w​e​b​s​i​t​e​,​ ​p​l​e​a​s​e​ ​c​o​n​t​a​c​t​ ​t​h​e​ ​R​a​i​n​ ​T​e​a​m​.
			 */
			message3: string
		}
		'422': {
			/**
			 * U​n​p​r​o​c​e​s​s​a​b​l​e​ ​E​n​t​i​t​y
			 */
			title: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​p​r​o​c​e​s​s​ ​t​h​e​ ​r​e​q​u​e​s​t​ ​f​o​r​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​r​e​a​s​o​n​s​:
			 */
			message1: string
		}
		'500': {
			/**
			 * I​n​t​e​r​n​a​l​ ​E​r​r​o​r
			 */
			title: string
			/**
			 * A​n​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d​ ​i​n​s​i​d​e​ ​t​h​e​ ​s​e​r​v​e​r​ ​f​o​r​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​r​e​a​s​o​n​s​:
			 */
			message1: string
			/**
			 * P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​ ​a​f​t​e​r​ ​a​ ​w​h​i​l​e​.
			 */
			message3: string
		}
		/**
		 * U​n​e​x​p​e​c​t​e​d​ ​E​r​r​o​r
		 */
		unexpectedErr: string
		/**
		 * A​n​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d​ ​i​n​ ​t​h​e​ ​p​a​g​e​ ​f​o​r​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​r​e​a​s​o​n​:
		 */
		otherMessage1: string
		/**
		 * R​e​a​s​o​n​ ​u​n​k​n​o​w​n​.
		 */
		otherMessage2: string
		/**
		 * A​ ​u​s​e​r​ ​a​c​c​o​u​n​t​ ​c​o​u​l​d​ ​n​o​t​ ​b​e​ ​f​o​u​n​d​.
		 */
		noUserData: string
		/**
		 * P​l​e​a​s​e​ ​s​t​a​r​t​ ​t​h​e​ ​p​r​o​c​e​s​s​ ​o​v​e​r​ ​f​r​o​m​ ​t​h​e​ ​b​e​g​i​n​n​i​n​g​.
		 */
		startOverMsg3: string
		/**
		 * A​t​t​e​m​p​t​e​d​ ​t​o​ ​p​e​r​f​o​r​m​ ​a​n​ ​u​n​a​u​t​h​o​r​i​z​e​d​ ​o​p​e​r​a​t​i​o​n​.
		 */
		unauthOps: string
		/**
		 * I​n​v​a​l​i​d​ ​c​a​p​t​u​r​e​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
		 */
		invalidCaptcha: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​c​o​m​m​u​n​i​c​a​t​e​ ​w​i​t​h​ ​R​a​i​n​ ​A​P​I​ ​f​o​r​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​r​e​a​s​o​n​:
		 */
		failedApiMsg1: string
		/**
		 * N​o​ ​t​e​m​p​o​r​a​r​i​l​y​ ​s​t​o​r​e​d​ ​d​a​t​a​ ​e​x​i​s​t​s​.
		 */
		noPreRegData: string
		/**
		 * Y​o​u​r​ ​s​e​s​s​i​o​n​ ​m​a​y​ ​h​a​v​e​ ​e​x​p​i​r​e​d​.
		 */
		sessionExpired: string
		/**
		 * U​n​d​e​f​i​n​e​d​ ​p​a​r​a​m​e​t​e​r​s​.
		 */
		paramsUndefined: string
		/**
		 * I​n​v​a​l​i​d​ ​d​a​t​a​ ​w​a​s​ ​p​a​s​s​e​d​.
		 */
		passedInvalidData: string
		oauth: {
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​a​u​t​h​o​r​i​z​e​ ​y​o​u​r​ ​d​i​s​c​o​r​d​ ​a​c​c​o​u​n​t​ ​f​o​r​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​r​e​a​s​o​n​s​:
			 */
			message1: string
			/**
			 * T​h​e​ ​d​a​t​a​ ​r​e​q​u​i​r​e​d​ ​f​o​r​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​ ​d​o​e​s​ ​n​o​t​ ​e​x​i​s​t​.
			 */
			noDataForAuth: string
			/**
			 * A​c​c​e​s​s​ ​t​o​ ​t​h​i​s​ ​p​a​g​e​ ​i​s​ ​o​n​l​y​ ​p​o​s​s​i​b​l​e​ ​v​i​a​ ​d​i​s​c​o​r​d​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​.
			 */
			noDataForAuthMsg3: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​g​e​t​ ​d​i​s​c​o​r​d​ ​t​o​k​e​n​.
			 */
			failedGetToken: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​g​e​t​ ​d​a​t​a​ ​f​o​r​ ​a​u​t​h​o​r​i​z​e​d​ ​u​s​e​r​.
			 */
			failedGetUser: string
		}
		register: {
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​r​e​g​i​s​t​e​r​ ​f​o​r​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​r​e​a​s​o​n​s​:
			 */
			failedRegisterMsg1: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​u​s​e​r​ ​d​a​t​a​ ​f​o​r​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​r​e​a​s​o​n​s​:
			 */
			failedCreateUser: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​c​h​a​r​a​c​t​e​r​ ​d​a​t​a​ ​f​o​r​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​r​e​a​s​o​n​s​:
			 */
			failedCreateCharacter: string
		}
		login: {
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​l​o​g​i​n​ ​f​o​r​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​r​e​a​s​o​n​s​:
			 */
			failedLoginMsg1: string
		}
		resetPassword: {
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​r​e​s​e​t​ ​t​h​e​ ​p​a​s​s​w​o​r​d​ ​f​o​r​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​r​e​a​s​o​n​:
			 */
			failedResetMsg1: string
			/**
			 * T​h​e​ ​g​a​m​e​ ​a​c​c​o​u​n​t​ ​l​i​n​k​e​d​ ​t​o​ ​y​o​u​r​ ​d​i​s​c​o​r​d​ ​a​c​c​o​u​n​t​ ​y​o​u​ ​l​o​g​g​e​d​ ​i​n​ ​t​o​ ​d​u​r​i​n​g​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​ ​c​o​u​l​d​ ​n​o​t​ ​b​e​ ​f​o​u​n​d​.
			 */
			noLinkedUser: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​s​e​n​d​ ​d​i​r​e​c​t​ ​m​e​s​s​a​g​e​ ​t​o​ ​a​u​t​h​o​r​i​s​e​d​ ​u​s​e​r​.
			 */
			failedSendDM: string
			/**
			 * Y​o​u​ ​m​a​y​ ​h​a​v​e​ ​d​i​s​a​b​l​e​d​ ​t​h​e​ ​s​e​t​t​i​n​g​ ​"​A​l​l​o​w​ ​d​i​r​e​c​t​ ​m​e​s​s​a​g​e​s​ ​f​r​o​m​ ​s​e​r​v​e​r​ ​m​e​m​b​e​r​s​"​ ​w​i​t​h​i​n​ ​P​r​i​v​a​c​y​ ​&​ ​S​a​f​e​t​y​ ​s​e​t​t​i​n​g​s​,​<​b​r​>​o​r​ ​y​o​u​ ​m​a​y​ ​n​o​t​ ​h​a​v​e​ ​j​o​i​n​e​d​ ​t​h​e​ ​o​f​f​i​c​i​a​l​ ​R​a​i​n​ ​S​e​r​v​e​r​ ​d​i​s​c​o​r​d​.
			 */
			failedSendDMMsg3: string
		}
		linkDiscord: {
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​l​i​n​k​ ​y​o​u​r​ ​d​i​s​c​o​r​d​ ​a​c​c​o​u​n​t​ ​f​o​r​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​r​e​a​s​o​n​:
			 */
			failedLinkMsg1: string
			/**
			 * P​a​s​s​w​o​r​d​ ​d​o​e​s​ ​n​o​t​ ​m​a​t​c​h​.
			 */
			notMatchPass: string
			/**
			 * Y​o​u​r​ ​d​i​s​c​o​r​d​ ​a​c​c​o​u​n​t​ ​i​s​ ​a​l​r​e​a​d​y​ ​l​i​n​k​e​d​ ​t​o​ ​t​h​e​ ​g​a​m​e​ ​a​c​c​o​u​n​t​.
			 */
			existLinkedUser: string
			/**
			 * T​h​e​ ​c​h​a​r​a​c​t​e​r​ ​"​{​n​a​m​e​}​"​ ​d​o​e​s​ ​n​o​t​ ​e​x​i​s​t​ ​i​n​ ​t​h​e​ ​u​s​e​r​ ​a​c​c​o​u​n​t​.
			 * @param {string} name
			 */
			noCharacter: RequiredParams<'name'>
			/**
			 * Y​o​u​ ​h​a​v​e​ ​n​o​t​ ​j​o​i​n​e​d​ ​t​h​e​ ​o​f​f​i​c​i​a​l​ ​R​a​i​n​ ​S​e​r​v​e​r​ ​d​i​s​c​o​r​d​.
			 */
			notJoinedDiscord: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​a​d​d​ ​"​R​e​g​i​s​t​e​r​e​d​"​ ​r​o​l​e​.
			 */
			failedAddRole: string
			/**
			 * F​o​r​ ​a​d​m​i​n​i​s​t​r​a​t​o​r​s​:​ ​c​h​e​c​k​ ​t​h​a​t​ ​t​h​e​ ​b​o​t​'​s​ ​p​e​r​m​i​s​s​i​o​n​s​ ​a​r​e​ ​c​o​r​r​e​c​t​.
			 */
			failedAddRoleMsg3: string
		}
	}
}

export type TranslationFunctions = {
	/**
	 * Rain Server
	 */
	serverTitle: () => LocalizedString
	/**
	 * Rain Server is not affiliated with Capcom Co., Ltd. or any of its subsidiaries. <br>This community is based on the cooperation of numerous volunteers, and no revenue of any sort is generated through this community.
	 */
	footerText: () => LocalizedString
	/**
	 * This site is protected by Cloudflare Turnstile and Cloudflare's <a target="_blank" rel="noopener noreferrer" href="https://www.cloudflare.com/privacypolicy/" style="text-decoration: underline; color: #32d9f3;">Privacy Policy</a> and <a target="_blank" rel="noopener noreferrer" href="https://www.cloudflare.com/website-terms/" style="text-decoration: underline; color: #32d9f3;">Terms of Service</a> apply.
	 */
	captchaText: () => LocalizedString
	header: {
		/**
		 * English
		 */
		currentLang: () => LocalizedString
		langSelectArea: {
			ja: {
				/**
				 * 日本語
				 */
				mainName: () => LocalizedString
				/**
				 * Japanese
				 */
				subName: () => LocalizedString
			}
			en: {
				/**
				 * English
				 */
				mainName: () => LocalizedString
				/**
				 * English
				 */
				subName: () => LocalizedString
			}
		}
	}
	register: {
		/**
		 * Register
		 */
		metaTitle: () => LocalizedString
		/**
		 * This is the registration page for the Rain Server version of Monster Hunter Frontier Online.
		 */
		metaDesc: () => LocalizedString
		/**
		 * Create an Account
		 */
		title: () => LocalizedString
		stage1Text: {
			/**
			 * Username <span>(6-20 charcters, may only contain alphanumeric characters)</span>
			 */
			'0': () => LocalizedString
			/**
			 * Password <span>(10-32 charcters)</span>
			 */
			'1': () => LocalizedString
			/**
			 * Confirm Password
			 */
			'2': () => LocalizedString
			/**
			 * Password Strength
			 */
			'3': () => LocalizedString
		}
		/**
		 * Register
		 */
		stage1Btn: () => LocalizedString
		/**
		 * </p>Registration has not been completed yet.<br>Click "Redirect" button below to move to the discord authorization page and complete the discord account linking.</p><p style="color: #ff1e1e;">* To link your account, you must be a member of the official Rain Server discord. You can join <a style="text-decoration: underline;" href="https://discord.gg/TcpkpUpeGw" target="_blank" rel="noopener noreferrer">here</a>.
		 */
		stage2Text: () => LocalizedString
		/**
		 * Redirect
		 */
		stage2Btn: () => LocalizedString
		/**
		 * <p>A verification code has been sent to your direct message.<br>Please confirm that you have received the code and proceed to the input page.</p><p style="color: #ff1e1e;">This procedure should be completed within {min} minutes of this.</p>
		 */
		stage1_1Text: (arg: { min: number }) => LocalizedString
		passwordStrength: {
			/**
			 * Too Weak
			 */
			'0': () => LocalizedString
			/**
			 * Weak
			 */
			'1': () => LocalizedString
			/**
			 * Medium
			 */
			'2': () => LocalizedString
			/**
			 * Strong
			 */
			'3': () => LocalizedString
		}
		passwordStrengthList: {
			/**
			 * Your password needs to:
			 */
			'0': () => LocalizedString
			/**
			 * contain 10-32 characters.
			 */
			'1': () => LocalizedString
			/**
			 * contain both lower (a-z) and upper case letters (A-Z).
			 */
			'2': () => LocalizedString
			/**
			 * contain at least one number (0-9).
			 */
			'3': () => LocalizedString
			/**
			 * contain at least one symbol ({symbol}).
			 */
			'4': (arg: { symbol: string }) => LocalizedString
		}
		/**
		 * Already have an account?
		 */
		haveAccount: () => LocalizedString
		/**
		 * Account creation and discord linking has been successfully completed.<br>Feel free to close this browser window.
		 */
		doneRegister: () => LocalizedString
		/**
		 * The user already exists.
		 */
		userExist: () => LocalizedString
		/**
		 * Enter your username correctly.
		 */
		invUsername: () => LocalizedString
		/**
		 * Your username may only contain alphanumeric characters. (6-20 charcters, A-Z, a-z, 0-9)
		 */
		invUsernameChar: () => LocalizedString
		/**
		 * Enter your password correctly.
		 */
		invPassword: () => LocalizedString
		/**
		 * Your passwords must be "strong" and 10-32 characters.
		 */
		invalidPasswordStrength: () => LocalizedString
		/**
		 * Your password and confirmation password must match.
		 */
		invConfPassword: () => LocalizedString
	}
	login: {
		/**
		 * Log In
		 */
		title: () => LocalizedString
		/**
		 * This is the login page for the Rain Server version of Monster Hunter Frontier Online.
		 */
		metaDesc: () => LocalizedString
		/**
		 * Username
		 */
		usernameLabel: () => LocalizedString
		/**
		 * Password
		 */
		passwordLabel: () => LocalizedString
		/**
		 * Remember Me
		 */
		rememberMe: () => LocalizedString
		/**
		 * Forgot Password?
		 */
		forgotPassword: () => LocalizedString
		/**
		 * Don't have an account?
		 */
		notRegister: () => LocalizedString
		/**
		 * Log In
		 */
		buttonLabel: () => LocalizedString
		/**
		 * The account with the entered username does not exist.
		 */
		noUser: () => LocalizedString
		/**
		 * Password is incorrect.
		 */
		incPassword: () => LocalizedString
		/**
		 * Captcha validation in progress... Please wait a moment.
		 */
		captchaInProg: () => LocalizedString
	}
	resetPassword: {
		/**
		 * Forgot Password
		 */
		metaTitle: () => LocalizedString
		/**
		 * This is the account linking page for the Rain Server version of Monster Hunter Frontier Online. If you have lost your password, you can reset a new one from this page.
		 */
		metaDesc: () => LocalizedString
		/**
		 * Reset Password
		 */
		title: () => LocalizedString
		/**
		 * Confirm
		 */
		stage1Btn: () => LocalizedString
		/**
		 * Verification Code Input Field
		 */
		stage2Text: () => LocalizedString
		/**
		 * Verify
		 */
		stage2Btn: () => LocalizedString
		stage3Text: {
			/**
			 * Username
			 */
			'0': () => LocalizedString
			/**
			 * New Password <span>(10-32 charcters)</span>
			 */
			'1': () => LocalizedString
			/**
			 * Confirm New Password
			 */
			'2': () => LocalizedString
		}
		/**
		 * Reset
		 */
		stage3Btn: () => LocalizedString
		/**
		 * Your password has been successfully reset.<br>You can now log in with your new password.
		 */
		doneReset: () => LocalizedString
		/**
		 * The code does not match.
		 */
		codeNotMatch: () => LocalizedString
		/**
		 * Please enter the following verification code to complete this procedure.
	Access to the "{site}" site is valid for {time} minutes immediately after this code is issued. Also, if you close the tab or refresh the site, you will not be able to access the site.
		 */
		verifCodeDesc: (arg: { site: string, time: number }) => LocalizedString
	}
	linkDiscord: {
		/**
		 * Discord Account Linking
		 */
		metaTitle: () => LocalizedString
		/**
		 * This is the account linking page for the Rain Server version of Monster Hunter Frontier Online. You can link your discord account to your game account.
		 */
		metaDesc: () => LocalizedString
		/**
		 * Account Linking
		 */
		title: () => LocalizedString
		/**
		 * Next
		 */
		stage3Btn: () => LocalizedString
		/**
		 * User ID (Discord)
		 */
		discordUserIDLabel: () => LocalizedString
		/**
		 * Username (Discord)
		 */
		discordUsernameLabel: () => LocalizedString
		/**
		 * Select the Character to Be Linked
		 */
		characterName: () => LocalizedString
		opitonText: {
			/**
			 * HR: 
			 */
			'0': () => LocalizedString
			/**
			 * GR: 
			 */
			'1': () => LocalizedString
			/**
			 * Weapon Type: 
			 */
			'2': () => LocalizedString
		}
		/**
		 * The discord account has been successfully linked.<br>Feel free to close this browser window.
		 */
		doneLinkDiscord: () => LocalizedString
		/**
		 * Link
		 */
		buttonLabel: () => LocalizedString
		/**
		 * Discord
		 */
		discordLabel: () => LocalizedString
		/**
		 * Frontier
		 */
		frontierLabel: () => LocalizedString
		/**
		 * This character has already been linked.
		 */
		existLinkedChar: () => LocalizedString
		/**
		 * This user account is already linked to another discord account.
		 */
		userLinked: () => LocalizedString
	}
	maintenance: {
		/**
		 * Under Maintenance
		 */
		title: () => LocalizedString
		/**
		 * This site is currently under maintenance and cannot be accessed.
		 */
		message1: () => LocalizedString
		/**
		 * Maintenance will end on: 
		 */
		message2: () => LocalizedString
		/**
		 * Please wait for a while until the end of maintenance is announced.
		 */
		message3: () => LocalizedString
	}
	error: {
		'400': {
			/**
			 * Bad Request
			 */
			title: () => LocalizedString
			/**
			 * Failed to process the request for the following reasons:
			 */
			message1: () => LocalizedString
		}
		'401': {
			/**
			 * Unauthorized
			 */
			title: () => LocalizedString
		}
		'403': {
			/**
			 * Forbidden
			 */
			title: () => LocalizedString
			/**
			 * You are not allowed to access this page for the following reason:
			 */
			message1: () => LocalizedString
			message2: {
				/**
				 * The user accessing this page is not Rain Administrators.
				 */
				'0': () => LocalizedString
			}
			/**
			 * If you find any problems with our website, please contact the Rain Team.
			 */
			message3: () => LocalizedString
		}
		'404': {
			/**
			 * Not Found
			 */
			title: () => LocalizedString
			/**
			 * The requested page was not found for the following reason:
			 */
			message1: () => LocalizedString
			message2: {
				/**
				 * The page file does not exist.
				 */
				'0': () => LocalizedString
				/**
				 * The page has been moved or deleted.
				 */
				'1': () => LocalizedString
				/**
				 * The URL was not correct or has been updated.
				 */
				'2': () => LocalizedString
			}
			/**
			 * If you find any problems with our website, please contact the Rain Team.
			 */
			message3: () => LocalizedString
		}
		'422': {
			/**
			 * Unprocessable Entity
			 */
			title: () => LocalizedString
			/**
			 * Failed to process the request for the following reasons:
			 */
			message1: () => LocalizedString
		}
		'500': {
			/**
			 * Internal Error
			 */
			title: () => LocalizedString
			/**
			 * An error occurred inside the server for the following reasons:
			 */
			message1: () => LocalizedString
			/**
			 * Please try again after a while.
			 */
			message3: () => LocalizedString
		}
		/**
		 * Unexpected Error
		 */
		unexpectedErr: () => LocalizedString
		/**
		 * An error occurred in the page for the following reason:
		 */
		otherMessage1: () => LocalizedString
		/**
		 * Reason unknown.
		 */
		otherMessage2: () => LocalizedString
		/**
		 * A user account could not be found.
		 */
		noUserData: () => LocalizedString
		/**
		 * Please start the process over from the beginning.
		 */
		startOverMsg3: () => LocalizedString
		/**
		 * Attempted to perform an unauthorized operation.
		 */
		unauthOps: () => LocalizedString
		/**
		 * Invalid capture. Please try again.
		 */
		invalidCaptcha: () => LocalizedString
		/**
		 * Failed to communicate with Rain API for the following reason:
		 */
		failedApiMsg1: () => LocalizedString
		/**
		 * No temporarily stored data exists.
		 */
		noPreRegData: () => LocalizedString
		/**
		 * Your session may have expired.
		 */
		sessionExpired: () => LocalizedString
		/**
		 * Undefined parameters.
		 */
		paramsUndefined: () => LocalizedString
		/**
		 * Invalid data was passed.
		 */
		passedInvalidData: () => LocalizedString
		oauth: {
			/**
			 * Failed to authorize your discord account for the following reasons:
			 */
			message1: () => LocalizedString
			/**
			 * The data required for authorization does not exist.
			 */
			noDataForAuth: () => LocalizedString
			/**
			 * Access to this page is only possible via discord authorization.
			 */
			noDataForAuthMsg3: () => LocalizedString
			/**
			 * Failed to get discord token.
			 */
			failedGetToken: () => LocalizedString
			/**
			 * Failed to get data for authorized user.
			 */
			failedGetUser: () => LocalizedString
		}
		register: {
			/**
			 * Failed to register for the following reasons:
			 */
			failedRegisterMsg1: () => LocalizedString
			/**
			 * Failed to create user data for the following reasons:
			 */
			failedCreateUser: () => LocalizedString
			/**
			 * Failed to create character data for the following reasons:
			 */
			failedCreateCharacter: () => LocalizedString
		}
		login: {
			/**
			 * Failed to login for the following reasons:
			 */
			failedLoginMsg1: () => LocalizedString
		}
		resetPassword: {
			/**
			 * Failed to reset the password for the following reason:
			 */
			failedResetMsg1: () => LocalizedString
			/**
			 * The game account linked to your discord account you logged in to during authorization could not be found.
			 */
			noLinkedUser: () => LocalizedString
			/**
			 * Failed to send direct message to authorised user.
			 */
			failedSendDM: () => LocalizedString
			/**
			 * You may have disabled the setting "Allow direct messages from server members" within Privacy & Safety settings,<br>or you may not have joined the official Rain Server discord.
			 */
			failedSendDMMsg3: () => LocalizedString
		}
		linkDiscord: {
			/**
			 * Failed to link your discord account for the following reason:
			 */
			failedLinkMsg1: () => LocalizedString
			/**
			 * Password does not match.
			 */
			notMatchPass: () => LocalizedString
			/**
			 * Your discord account is already linked to the game account.
			 */
			existLinkedUser: () => LocalizedString
			/**
			 * The character "{name}" does not exist in the user account.
			 */
			noCharacter: (arg: { name: string }) => LocalizedString
			/**
			 * You have not joined the official Rain Server discord.
			 */
			notJoinedDiscord: () => LocalizedString
			/**
			 * Failed to add "Registered" role.
			 */
			failedAddRole: () => LocalizedString
			/**
			 * For administrators: check that the bot's permissions are correct.
			 */
			failedAddRoleMsg3: () => LocalizedString
		}
	}
}

export type Formatters = {}
