name: 'Rain Auth'
on:
    push:
        branches:
            - development
    pull_request:
        branches:
            - development
        types:
            - opened
            - synchronize
            - closed

jobs:
    build-for-development:
        runs-on: ubuntu-latest
        env:
            DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}
            DIRECT_URL: ${{ secrets.DEV_DIRECT_URL }}
            ADMIN_CREDENTIALS: ${{ secrets.ADMIN_CREDENTIALS }}
            COOKIES_DOMAIN: ${{ secrets.COOKIES_DOMAIN }}
            PUBLIC_MAIN_DOMAIN: ${{ secrets.DEV_MAIN_DOMAIN }}
            PUBLIC_AUTH_DOMAIN: ${{ secrets.DEV_AUTH_DOMAIN }}
            DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
            DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
            DISCORD_CALLBACK_URI: ${{ secrets.DEV_DISCORD_CALLBACK_URI }}
            DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
            PUBLIC_TURNSTILE_SITE_KEY: ${{ secrets.TURNSTILE_SITE_KEY }}
            TURNSTILE_SECRET_KEY: ${{ secrets.TURNSTILE_SECRET_KEY }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              id: pnpm-install
              with:
                  version: 8
                  run_install: false

            - name: Install dependencies
              run: pnpm i
            
            - name: Prisma generate
              run: npx prisma generate --no-engine

            - name: Build
              run: pnpm build

            - name: Deploy on Cloudflare Development
              if: github.event_name == 'push' || github.event.pull_request.merged
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  accountId: ${{ secrets.CF_ACCOUNT_ID }}
                  command: deploy --name auth_dev
